-- This script is in development.
-- Step 1: Detect when a new item comes out and open the item's page, Done
-- Step 2: Buy the item once, then check if the item is actually good based on timer or quantity
