-- This script was protected using the MoonVeil Obfuscator v1.2.1 [https://moonveil.cc]

local _a,Na,B=pairs,getmetatable,type;
local z,I,va,q,xa,K,ga
q,xa={[-9209]=-7289,[16606]=19778},function(Qa)
    return q[Qa- -15737]
end
I=xa(869)
repeat
    while true do
        if I==-1312432986+1312452764 then
            K=(getfenv());
            ga,va,z=(string.char),(string.byte),(bit32 .bxor);
            I=xa(-24946);
            break;
        end
    end
until I==4.7474740090485281e-06*-1535342792
local p,_=K[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('B\4H\0','%e')][(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\16\138&C\151%\153;s\151','W\239R\16\242')](K[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('B\4H\0','%e')],(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\202S,\184\163\231U.\161\147\231',"\130\'X\200\240")),K[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\218zl\219zv\203','\189\31\24')]()[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('r\213\185r\213\163c','\21\176\205')]
local l,ea,Va,Ia,ka,L=_()[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('n9\181\231[\27\181\233[','>U\212\132')],K[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('k\6\208j\6\202z','\fc\164')]()[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('D\186\220\149\146l\160V\171\199\130\132h\174F','#\223\168\240\234\t\195')],K[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('L\129\221M\129\199]','+\228\169')]()[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\128F\1\57\54\26x?\140Z\1\52\55\aq4','\233\"dWBs\30F')],K[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('%]\154$]\128\52','B8\238')]()[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\206\49\179\201\49\177\200','\188T\194')],K[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('d\135\te\135\19u','\3\226}')]()[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\152&\30\151\52\3\155','\255Cj')],K[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\252\175\163\253\175\185\237','\155\202\215')]()[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\190\154\203i\172\221\20\24\184\135\197s\173\213\5\21','\215\233\173\28\194\190\96q')]
local function w(g,Ra)
    local P,ua,ia
    ua,P={[-18278]=-20533},function(c)
        return ua[c- -13905]
    end
    ia=P(-32183)
    repeat
        while true do
            if ia==-2.8897160901158125e-05*710554233 then
                return{[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\224\247\227\243','\142\150')]=g,[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\154\235\128\255\137','\236\138')]=Ra,[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\bA\129\bA\136','a/\237')]=true}
            end
        end
    until ia==1285819962+-1285820408
end
local function V(R)
    local E,Q,Ta
    E,Q={[-16054]=2575},function(la)
        return E[la- -6472]
    end
    Ta=Q(-22526)
    repeat
        while true do
            if Ta==1972034057-1972031482 then
                return K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\215ky*\206fr-','\163\4\23_')]((function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\201\129','\249')..R[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('U#I)y','\1L')](R))
            end
        end
    until Ta==-278042061- -278012417
end
if not(not ka and Ia)then
else
    local H,Aa,u
    u,Aa={[-10243]=-17916,[-22836]=23366},function(Sa)
        return u[Sa- -15377]
    end
    H=Aa(-38213)
    repeat
        while true do
            if H==-34794697026908/-1489116538 then
                ka=function()
                    local N,Ba,y,Pa,C,wa,Pa,Ja,Ua,N,Ya,S,ba,e
                    S,ba={[546]=31010,[-16513]=15163,[-11373]=14767,[-24506]=31010,[26340]=-1847,[24749]=32572,[18763]=-991,[1804]=-28586,[11686]=-991,[30961]=-22068,[-3799]=13500,[-11438]=-31888,[23851]=-25807,[29029]=14767,[20710]=14767,[17634]=14767,[24465]=15163,[-25631]=15163,[7908]=15163,[9652]=15163,[24839]=15163,[-23909]=15163,[16852]=15163},function(k)
                        return S[k+9295]
                    end
                    e=ba(14556)
                    repeat
                        while true do
                            if e==-8368758914432/262442264 then
                                Ya,C,Ba=wa.__iter(Ya)
                                e=ba(-1387)
                            elseif e==-1749042523- -1749016716 then
                                y,Ja='',Ia({[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\215\240\238','\130')]=(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)("\216Y\130\167\153$\164\49\f\'R\192O\159\185\196q\249yK4C\196",'\176-\246\215\234\30\139\30dS&'),[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\n\138Z/\128J','G\239.')]=(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\178\176\161','\245')})[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\18\173\52\187','P\194')];
                                Ua=p[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('8N\193\141\157\23~\225\167\188','r\29\142\195\217')](p,Ja);
                                Ya,C,Ba=Ua[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\15)R\3)A\20','gL3')];
                                if B(Ya)~='function'then
                                    e=ba(15454)
                                    break
                                end;
                                e=ba(-34926);
                            elseif e==-1304427330- -1304440830 then
                                return y
                            elseif e==3.1322219508314306e-05*-704547773 then
                                y=Pa
                                e=-657105692- -657119192
                                break
                            elseif e==-31376361495213/-2069271351 then
                                N,Pa=Ya(C,Ba);
                                Ba=N;
                                if Ba==nil then
                                    e=ba(-13094)
                                else
                                    e=ba(17045)
                                end
                            elseif e==-584501622+584499775 then
                                if N[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\137\198\146\204\151','\229\169')](N)[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\5\228\r\233','c\141')](N[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\137\198\146\204\151','\229\169')](N),(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\247ZS\n\n\227CO\4\1\229','\145\51=mo'))then
                                    e=ba(21666)
                                    break
                                end
                                e=ba(7557)
                            elseif e==990532308-990560894 then
                                Ya,C,Ba=_a(Ya)
                                e=ba(357)
                            elseif e==1200010247+-1199977675 then
                                wa=Na(Ya);
                                if wa~=nil and wa.__iter~=nil then
                                    e=ba(-20733)
                                    break
                                elseif B(Ya)==(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\n,\28!\27','~M')then
                                    e=ba(-7491)
                                    break
                                end
                                e=ba(15544)
                            end
                        end
                    until e==1.5399133681962516e-05*1771463289
                end
                H=Aa(-25620)
                break
            end
        end
    until H==-1614056504+1614038588
end
local v=ka()
local function Z(La)
    local X,Fa,f,U,F
    F,U={[21312]=-19836,[-11498]=5552,[7394]=5328,[7823]=5328,[-8861]=13012,[31427]=-30861,[-5631]=21108,[3535]=5552,[-23701]=-19836,[-17011]=-10280},function(Oa)
        return F[Oa+26468]
    end
    X=U(-43479)
    repeat
        while true do
            if X==-1.054251349403394e-05*-2002179083 then
                return
            elseif X==1471190117-1471184565 then
                f=La[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\177\144#\155\157\53','\247\249F')];
                if not f then
                    X=U(-35329)
                    break
                end;
                X=U(-5156);
            elseif X==-2179052730800/211970110 then
                if not Ia then
                    X=U(-32099)
                    break
                end
                X=U(-18645)
            elseif X==0.00021965227111665376*-140499344 then
                return
            elseif X==2.4010263261836388e-05*-826146710 then
                K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('eystt','\17\24')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\189\141\154\177\145\157','\212\227\233')](f,w((function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('?\253\189\177\247\234\138:\251\189\171\238\241\196','l\158\207\216\135\158\170'),_()[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)("U\234\191=\224PP\236\191\'\249Kh",'\6\137\205T\144$')]));
                K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\25N\15C\b','m/')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\201\157\29\197\129\26','\160\243n')](f,w((function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\1\22\198\221\49\26\204\204','Dn\163\190'),if ea then ea()else Va()));
                K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\167\158\177\147\182','\211\255')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\226L\239\238P\232','\139\"\156')](f,w((function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('i\165\t\188?I\167\5\183\57',' \193l\210K'),v));
                K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)("\215\'\193*\198",'\163F')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\203w%\199k\"','\162\25V')](f,w((function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('K\209\193\148}\210\210\141','\27\189\160\224'),K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\161!\171%','\198@')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\181\160#zj\128\179>Jj','\242\197W)\15')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\161!\171%','\198@')],(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('M\246,\249\96\180\142fl\214,\249_\179\157v','\24\133I\139)\218\254\19'))[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\154XY\133\0\188IK\186\30\176','\221=-\213l')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\161!\171%','\198@')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\181\160#zj\128\179>Jj','\242\197W)\15')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\161!\171%','\198@')],(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('M\246,\249\96\180\142fl\214,\249_\179\157v','\24\133I\139)\218\254\19')))[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\221:\254>','\147[')]))
                Fa={[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)(',\a6\235\55\21>\252','YtS\153')]=La[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\199\190>\246\252\172\54\225','\146\205[\132')],[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\175\188L\133@\188\149X\131M','\206\202-\241!')]=(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('/#\231\20hu%\180KsB\25h\130\5\210s\153\27#H\25\132\49{Q\31&\169R\150&\214@\29\253wg\246\218\195v\153\48y\203\255\199yu\96\171K.vi\172\30q\28\5;\142\23\132)\210Ls\b\b\153\55-\5T.\250Y\192\55\155\19\26\248k%\161\137\201\55\201\127/\196\243\206qq','GW\147d\27O\n\155(\23,7\f\235v\177\28\235\127B8i\170R\20<0O\202=\248U\249q.\207EU\207\238\246D\160\5J\249\199\254H'),[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\137[/\137R>','\236\54M')]={{[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\174\175\174\170\191','\218\198')]=l,[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\224\29\239\29\241','\131r')]=V(La[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('E\137j\137t','\6\230')]),[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('L\138YF\135O','*\227<')]=f}}}
                return K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\253\5\236\n\225','\141f')](Ia,{[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\174\137\151','\251')]=La[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)("\30\57\'",'K')],[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\197y\227o','\135\22')]=p[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\" B\4\129\6\16b.\161','hs\rJ\196')](p,Fa),[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\179|!\150v1','\254\25U')]=(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\202\235\201\240','\154\164'),[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\170_r\134_a\145','\226:\19')]={[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\156\14W\214i1\171Lm\219|:','\223a9\162\f_')]=(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\180\133\243\2\171R\169\189\188\154\237A\168B\167\167','\213\245\131n\194\49\200\201')}})
            elseif X==10700861871888/2008420021 then
                if L and L(Ia)then
                    X=U(4959)
                    break
                end
                X=U(-22933)
            elseif X==1204267441-1204254429 then
                f={}
                X=U(-50169)
            end
        end
    until X==-572244040+572227669
end
local s={(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('*\255,\28u\t\201c\217\169\134HBR\208\1\2\212\221\210k\252\49\rpY\154\0\216\180\212DBB\227\24N\207\209\153','K\139Xy\24y\189C\173\198\166!,6\181y\"\186\180\190'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)("\193\14\245_\r\231\255\1&\142m\28\6H@\202\211@\217\195\128\r\232N\b\183\172b\'\147?\16\6Xj\194\135G\223\193\135",'\160z\129:\96\151\139!R\225Muh,%\178\243.\176\175'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\172S\163\237\244\141^\22\130Y\143B\130\254\227\137d\22\149\30','\255\54\209\155\145\255\ru\240\48'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\173\31[\203Z\v\173\14F\207^\30\155','\254z)\189?y'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\22M\208$j\241\t\v\31J\132ij\242\t\f\1','x\"\164\4\15\159f~'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('BS\15\ro\253\r\168\6\194\155\254\208\245\243\53\b\183\164=\241\255\162\141\202\188\174\14\96P]\26YDm\225\4\234\2\194\220\238\197\224\248\"\\\241\241\49\165\247\237\222\153\173\187\ni[\2','+=yl\3\148i\136g\176\252\139\189\144\157A(\148\149\29\133\144\130\170\185\217\218h\5>'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)("\192\194\\\200Z\186\171\188\6:\128\245\163Bt\154\143\252\185RR\237\200\194@\141\16\173\186\232-\'\197\253\161yp\134\203\224\181M\1\189",'\161\182(\173\55\202\223\156rU\160\156\205&\17\226\175\146\208>r\154')}
_()[(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\236F\229\25\253\96\3n\207g\254\v\251V\31~','\170\52\138j\137\"z\26')]=function()
    local ca,Xa,A,pa,oa
    oa,ca={[-18986]=-20979,[30019]=-11159,[-23445]=-20979,[-10943]=-19723,[23842]=-9769},function(Ka)
        return oa[Ka+28713]
    end
    pa=ca(-4871)
    repeat
        while true do
            if pa==-1815893719- -1815883950 then
                Z({[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\229*)c\222\56!t','\176YL\17')]=(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\225\187\231\\\21U\205\172\236L@W\145','\164\195\130?\96!'),[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\224\199\217','\181')]=(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\1v\197\199 =\165d]\223,\206[\138\234\153B\14\254 \145\198\5\199\"|\180\146w8\t9s\218\57\185\251m\199\164\184\189\225\49{\131\173-\216\181&6\131\1d\"\247l\177\180\30J\227\142\23L\239~\20\133*\216y\137\254\208f0\231X\146\130=\176 O\189\204O \16\48(\145a\253\152*\133\202\222\239\132|&\234\205h\140\201e3\227\28a&\199&\161\170\2','i\2\177\183S\a\138K9\182_\173\52\248\142\183!a\147\15\240\182l\232U\25\214\250\24WbJ\\\235\n\141\194X\240\147\136\141\215\tJ\179\148\31\239\132\23\2\172V1s\160\22\254\208'),[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\234\55\197\55\219','\169X')]=K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\tf\178%{\237','J\t\222')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\161\143\236\170\175\196\133','\199\253\131')](0*1362351106,-896357858+896358059,-712300003- -712300102)})
                Xa=_()[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('<b\151\140N\137\57d\151\150W\146\1','o\1\229\229>\253')]
                if Xa[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\188\186\173','\207')](Xa,-1759053571+1759053572,-1.7377653279403941e-09*-575451693)~=(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\189','\203')and Xa~=(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\a\140/\159\14\134=\218','C\233Y\191')then
                    pa=ca(1306)
                    break
                end
                pa=ca(-52158)
            elseif pa==-165116783- -165095804 then
                A=_()[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\228e\197\195\237\212\250\137\194j\206\196\245\216\214\136','\172\4\171\167\129\177\185\230')];
                A(K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('4\138>\142','S\235')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\145\195uQ\133\164\208ha\133','\214\166\1\2\224')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('4\138>\142','S\235')],(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\182Y3D\152\136@=t\152','\250\54T\23\253'))[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\233\190\222@\178\195\190\226F\167','\164\219\173\51\211')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\249u_\212\127R\206','\186\26\49')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('4\138>\142','S\235')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\145\195uQ\133\164\208ha\133','\214\166\1\2\224')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('4\138>\142','S\235')],(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\182Y3D\152\136@=t\152','\250\54T\23\253'))[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\233\190\222@\178\195\190\226F\167','\164\219\173\51\211')],function(a)
                    local Ca,b,O,n,Ha,n,b,za,ta,x,r
                    r,ta={[31660]=-13896,[11223]=-3503,[-26700]=-15830,[3282]=32564,[9022]=-6942,[-12417]=-4,[-13196]=-6942,[5947]=-6942,[-2087]=22526,[-3556]=27721,[11727]=3799,[25807]=-3503,[27374]=12458,[19594]=21241,[-11311]=-25601,[-20322]=-27143,[-25837]=-520,[12387]=21241,[-8022]=21241,[-10417]=21241,[-21781]=27721,[2028]=27721,[-21041]=27721,[27086]=27721,[-15134]=27721,[-16202]=27721,[24005]=27721,[5826]=27721,[-22693]=27721},function(Y)
                        return r[Y+-9622]
                    end
                    za=ta(-16215)
                    repeat
                        while true do
                            if za==-6.0770471340583015e-05*-535852352 then
                                return
                            elseif za==-1118365939+1118369738 then
                                Z({[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\228x\172\144\223j\164\135','\177\v\201\226')]=(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\t\245k^N\238]#B\15\230u]^\252\30>Q','J\148\a2,\143>Hb'),[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)(' \a\25','u')]=(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)("bg\207\216\254\152\209I\19\137\165\251\195g\183\195\142\251\"k\139\5\191P\177\\}\21\172\144?\a\25\182m\220\204\220\167\161V\26Q\157(\203\49\5/<u\0\51\50\174\15\172\49\193kp\96\222\235\216\149\156\'2\139\148\192\254#\129\136\181\205\30\16\136\56\185J\245CL\30\148\169?\3\\\179/\153\135\152\197\196%b\"\242@\205BT}m#Kv0\136\0\252\"\156VA",'\n\19\187\168\141\162\254fw\224\214\152\172\21\211\237\237\148OD\234u\214\127\198\57\31}\195\255Tt6\135^\232\244\235\159\147b.c\170\17\248\b6\31\vM2\28J\222y\207z\172\28'),[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\191<\144<\142','\252S')]=K[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\180*\128\152\55\223','\247E\236')][(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\28YO\23yg8','z+ ')](1808020073+-1808019992,-1.1455693560081748e-06*-103878477,-1425276643+1425276844),[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\26\51s0>e','\\Z\22')]={w((function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\138\0\246\205\160T\239\162A\223\211\176Z\254','\201a\154\161\194\53\140'),(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\21\21\21','u')..a..(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\f\f\f','l'))}})
                                za=ta(41282)
                                break
                            elseif za==-539026349- -539000748 then
                                O=Na(Ha);
                                if O~=nil and O.__iter~=nil then
                                    za=ta(-17078)
                                    break
                                elseif B(Ha)==(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\211\208\197\221\194','\167\177')then
                                    za=ta(-10700)
                                    break
                                end
                                za=ta(-13071)
                            elseif za==-16743802763779/-604011499 then
                                n,b=Ha(Ca,x);
                                x=n;
                                if x==nil then
                                    za=ta(21349)
                                else
                                    za=-2.1485765832727649e-05*1196001120
                                end
                            elseif za==1158408045+-1158435188 then
                                Ha,Ca,x=_a(Ha)
                                za=ta(15448)
                            elseif za==1288837807-1288853637 then
                                Ha,Ca,x=O.__iter(Ha)
                                za=ta(33627)
                            elseif za==-1858318825- -1858293128 then
                                if not(a[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)((function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\18s\26~','C\172'),(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('A\192','v'))](a,b))then
                                    za=ta(36708)
                                    break
                                else
                                    za=ta(12904)
                                    break
                                end
                                za=ta(-11419)
                            elseif za==405369993-405357535 then
                                Ha,Ca,x=s;
                                if B(Ha)~='function'then
                                    za=ta(-1689)
                                    break
                                end;
                                za=ta(-6580);
                            elseif za==-1292595457+1292594937 then
                                if not a[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\22\150\30\155','p\255')](a,(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\243\145\179','\17'))or not a[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\213\145\221\156','\179\248')](a,(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\207\241V\196\244\245C\198','\157\144/\162'))then
                                    za=ta(7535)
                                    break
                                end
                                za=-1558369132- -1558381590
                            elseif za==1.8798332806690438e-05*1198297755 then
                                return
                            end
                        end
                    until za==-1.0778408819899336e-05*1289244102
                end),(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('5S\217\152\141\235\174\211*9X\203\135\149\248\162\255,\0','t=\184\244\244\159\199\176Y'));
                A(K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\233\24\227\28','\142y')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('] C/\137h3^\31\137','\26E7|\236')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\233\24\227\28','\142y')],(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('I\176\253\96\185\238j','\25\220\156'))[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\165u9m\206^\199\144t7b\194B\242','\245\25X\20\171,\149')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\186\230\129\151\236\140\141','\249\137\239')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\233\24\227\28','\142y')][(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('] C/\137h3^\31\137','\26E7|\236')](K[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\233\24\227\28','\142y')],(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('I\176\253\96\185\238j','\25\220\156'))[(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\165u9m\206^\199\144t7b\194B\242','\245\25X\20\171,\149')],function(Wa)
                    local o,ra,d
                    o,d={[-1768]=9362,[-20327]=-14041,[17409]=-29168,[19667]=9362,[-19925]=7372},function(ya)
                        return o[ya+-3220]
                    end
                    ra=d(-16705)
                    repeat
                        while true do
                            if ra==1244754368-1244745006 then
                                Z({[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\23\4\235#,\22\227\52','Bw\142Q')]=(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('$\144\96\142\50\24\155\96\221-F','w\245\19\253['),[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\21\50,','@')]=(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)("\170\244\178q%.E%\244\15\221\196(\202:\150\v\211k\tO\23\171bA\'\242\49uj\254\252\"\218\203\147\17\156\201\151\183%\210\16\231\15u\16r\255U\255\177\136O\202f\148JO\177\248\190\52\27w\6;\199\49\158\247?\242j\254\55\203Q\\bW\247~z$\228\48Bh\209\215j\178\139\254v\146\174\245\206m\191\18\159l\127j.\173\'\132\246\185c\189N\236\55\2\136","\194\128\198\1V\20j\n\144f\174\167G\184^\184h\188\6&.g\194M6B\144Y\26\5\149\143\r\235\248\164 \171\248\162\135\23\224\'\212\57F\"D\200d\201\158\248:\141(\163\2w"),[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\239\242\192\242\222','\172\157')]=K[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\152\139J\180\150\21','\219\228&')][(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)("\151\0\15\156 \'\179",'\241r\96')](-1045931589+1045931738,206597291302/910120226,-2000534531+2000534786),[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\205\180\174\231\185\184','\139\221\203')]={w((function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('V\146\171\223,\174\218%\187\189\194\"\181\220','\5\247\216\172E\193\180'),`{K[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\28\21\5\28','qt')][(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\158\243\151\240\138','\248\159')](K[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\3\178\20\176','w\219')]()-_()[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\202\52#\225=f\247\2$\243&}','\153QP\146T\t')])} seconds`)}})
                                ra=d(-17107)
                                break
                            elseif ra==1477306100+-1477298728 then
                                if Wa~=K[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\236A\230E','\139 ')][(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\14\167\147B\185;\180\142r\185','I\194\231\17\220')](K[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\236A\230E','\139 ')],(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('\202NL\227G_\233','\154\"-'))[(function(Ga,D)
                                    local Ea=''
                                    for ja=0,#Ga-1 do
                                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                    end
                                    return Ea
                                end)('#i\r\186\"?j\15\162+\29','o\6n\219N')]then
                                    ra=d(20629)
                                    break
                                end;
                                ra=d(1452);
                            elseif ra==728766551+-728795719 then
                                return
                            end
                        end
                    until ra==14461968542539/-1029981379
                end),(function(Ga,D)
                    local Ea=''
                    for ja=0,#Ga-1 do
                        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                    end
                    return Ea
                end)('\243\24\189\16\154,&\171\5\3\215\5\175\21\140\54\n\166\18\53\214','\178v\220|\227XO\200vP'))
                pa=ca(-39656)
                break
            elseif pa==5.5453603715027096e-06*-2012312862 then
                return
            end
        end
    until pa==-35837976919877/1817065199
end
local Da={(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\254r~Y;a\160\149\192\241:\137\183UdO\183?9\24#g\228\146\210\230)\154\191^|\28','\151\28\b8W\b\196\181\161\131]\252\218\48\n;'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\175\182u\133\57\254\244\157\209\134B\t\236\140\160\246\226#\201x\235\160\150\213\154\22_\249\143\245\240','\149\131O\165X\138\128\248\188\246\54)\152\227\128'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\27\219\28\251\149t\222X\159\230|r\194I@\131sQ\132J\238\150=\157\20\145\245\127t\219^G\153\52U','r\181j\154\249\29\186x\254\148\27\a\175,.\247S'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('q\226\205\138F\245\252\138P','2\144\168\235'),(function(Ga,D)
    local Ea=''
    for ja=0,#Ga-1 do
        Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
    end
    return Ea
end)('\31\225\148\223\52\178\v\250\159\218/\160','\\\147\241\190@\215')}
local M,T,Ma
M,Ma={[22686]=19826,[17780]=-1102},function(h)
    return M[h- -4882]
end
T=Ma(12898)
repeat
    while true do
        if T==1435792022-1435793124 then
            _()[(function(Ga,D)
                local Ea=''
                for ja=0,#Ga-1 do
                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                end
                return Ea
            end)('\234>\180fc\131\25\244\135I\173\194(\183pQ\180\14\227\150h\163\194','\172L\219\21\23\193\96\128\226\1\204')]=function(ma,i)
                local fa,sa,aa,fa,J,ha,aa,na,qa,W,t,da,G,m
                qa,na={[-29794]=15439,[-806]=4542,[15383]=32572,[12697]=28306,[-846]=-16546,[-29551]=4542,[13145]=23990,[24119]=-25786,[-14944]=-17168,[3003]=4542,[-8323]=27639,[-5323]=32056,[-7116]=12721,[1690]=28063,[11519]=-12581,[-25502]=12721,[-17805]=32056,[-21315]=6977,[4935]=22858,[-10134]=-12581,[31906]=21722,[-7177]=-21024,[-30706]=21722,[26655]=28464,[-5255]=12721,[-12734]=9375,[606]=15439,[-24946]=4486,[-24237]=4542,[6620]=-12581,[-1396]=-12581,[17246]=-12581,[-4637]=-12581,[-2413]=28063,[3672]=28063,[19638]=28063,[-826]=-12581,[-19377]=-12581,[-2297]=-12581,[-29539]=-12581,[18987]=-12581,[-15755]=32056,[-10615]=21722},function(j)
                    return qa[j+22501]
                end
                m=na(-47447)
                repeat
                    while true do
                        if m==-1934884180- -1934907038 then
                            W=Na(J);
                            if W~=nil and W.__iter~=nil then
                                m=na(-35235)
                                break
                            elseif B(J)==(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\135\198\145\203\150','\243\167')then
                                m=na(-9356)
                                break
                            end
                            m=na(-3514)
                        elseif m==36072366993008/1660637464 then
                            if not G[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('t6k/s','\aF')](G,(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\b','2'))[-2869512006/-956504002]then
                                m=na(-7118)
                                break
                            end
                            m=na(-21895)
                        elseif m==-1915521914+1915554486 then
                            return
                        elseif m==24269935614758/-1929094318 then
                            aa,fa=J(da,t);
                            t=aa;
                            if t==nil then
                                m=na(-23347)
                            else
                                m=719599661-719596300
                            end
                        elseif m==1007210344+-1007182705 then
                            return
                        elseif m==-680779344+680803334 then
                            J,da,t=_a(J)
                            m=na(-52040)
                        elseif m==35606465198956/-1380844846 then
                            return
                        elseif m==-489960585- -489944039 then
                            ha=_()[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('id-\v\160&lb-\17\185=T',':\a_b\208R')];
                            if not(ha[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)((function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)("6\48\'",'\251'),(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\160','\30'))](ha,(-3552401200- -1747401163)+(1930997602-125997564),(-2.6546301881074097*526797377)/(-581959046-816493174))~=(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)((function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\194','\152'),(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\96','L')))then
                                m=na(-38256)
                                break
                            else
                                m=na(-30824)
                                break
                            end;
                            m=47653412364008/1486567643;
                        elseif m==-1.541937520080016e-05*1363479371 then
                            return
                        elseif m==-3.2311751344905027e-06*-1040178839 then
                            if not(G[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)((function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\5\168\r\165','\129\136'),(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\b\163','\234'))](G,fa))then
                                m=na(-23897)
                                break
                            else
                                m=na(-29678)
                                break
                            end
                            m=na(-27138)
                        elseif m==-445372783- -445404839 then
                            K[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\140G\139M','\248&')][(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('z\243h\244g','\t\131')](K[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)("P\'G:G",'5U')],G);
                            Z({[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\137[\185\218\178I\177\205','\220(\220\168')]=(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)("Q\215q6dA\187\'E\127=\253b xG\186n]*",'\29\184\16R\23\53\201N+\24'),[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('g@^','2')]=(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)("\148\254\50D\15\132\157\1\202Y\170\168\244\234\204I]v#\228\183\156)\166\"\130\178\203\196\139\247^Q@s\132\158 \182$w\182\4\f\163\157\228caMz.\135\204i\14\236 v\142\202\225\21d?\219\208W\218d\168\145\244\174\242\30Gzx\152\149\139\'\188-\157\133\229\233\183\206X9+\19\252\241]\236i\22\200\0^\252\250\153\54\5\26|*\216\197}&\240Ad\130\147",'\252\138F4|\190\178.\174\48\217\203\155\152\168g>\25N\203\214\236@\137U\231\208\163\171\228\156-~q@\178\166\20\128\16N\142\52:\145\172\209QT}J\28\168\252>_\186\25\6\246'),[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\140\228\163\228\189','\207\139')]=K[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\213\161#\249\188|','\150\206O')][(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\216[l\211{D\252','\190)\3')](1782494571-1782494401,2.5809688569943827e-08*1666041025,-40888720210/-950900470),[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\210\232\134\248\229\144','\148\129\227')]={w((function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\244(\31$L\216\199\232\214 ^\5M\222\218\243','\184G~@?\172\181\129'),(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('???','_')..G..(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\181\181\181','\213')),w((function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\4\162a%\174q','W\205\20'),i)}})
                            m=na(-43816)
                            break
                        elseif m==-1.4050610670946364e-05*-1098813451 then
                            J,da,t=Da;
                            if B(J)~='function'then
                                m=na(-17566)
                                break
                            end;
                            m=na(-41878);
                        elseif m==1.8731423897069885e-05*500495854 then
                            J,da,t=W.__iter(J)
                            m=na(-24798)
                        elseif m==-1.2673291977061205e-05*-353972749 then
                            sa,G=K[(function(Ga,D)
                                local Ea=''
                                for ja=0,#Ga-1 do
                                    Ea=Ea..ga(z(va(Ga,ja+1),va(D,ja%#D+1)))
                                end
                                return Ea
                            end)('\208\28\193\19\204','\160\127')](ma);
                            if not(sa or not G)then
                                m=na(-33116)
                                break
                            else
                                m=na(1618)
                                break
                            end
                            m=-1952434209- -1952455931
                        end
                    end
                until m==670290310-670283333
            end
            T=Ma(17804)
            break
        end
    end
until T==-33637458903508/-1696633658
